### ISSUE TITLE
Sub-subtasks

### ISSUE THREAD

**Issue by texastoland** [byteclubfr/npm-scripts-tree#5]
#### Given

``` json
"scripts": {
  "test": "npm-run-all -p test:*",
  "test:lint": "npm-run-all -p test:lint:*",
  "test:lint:eslint": "eslint src-js"
}
```
#### Expected

```
├─┬ test — npm-run-all -p test:*
│ └─┬ test:lint — npm-run-all -p test:lint:*
│   └── test:lint:eslint — eslint src-js
…
```
#### Given

``` json
"scripts": {
  "test": "npm-run-all -p test:**",
  "test:lint:eslint": "eslint src-js"
}
```
#### Expected

```
├─┬ test — npm-run-all -p test:**
│ └── test:lint:eslint — eslint src-js
…
```

**Comment by texastoland** [comment]
I'm not currently using [scripty](https://www.npmjs.com/package/scripty) but it just strictly follows this script naming convention.

**Comment by Delapouite** [comment]
Thanks for this request. To manually test it run `nst test/5.1.json` or `nst test/5.2.json`
https://github.com/byteclubfr/npm-scripts-tree/blob/master/test/5.1.json
https://github.com/byteclubfr/npm-scripts-tree/blob/master/test/5.2.json
